### ISSUE TITLE
how to fetching video source urls from a video

### ISSUE THREAD

**Issue by elmadkoun** [iphoting/youtube-dl-api-server-heroku#22]
how to fetching video source urls from a video
like this
https://api.uplayer.stream/gounlimitedto/api-fo-player.php?url=

from any gounlimited link like this

https://gounlimited.to/embed-zvb2mtxo0nof.html

pleas help

**Comment by iphoting** [comment]
Hi, it’s not a supported site: https://ytdl-org.github.io/youtube-dl/supportedsites.html
