### ISSUE TITLE
Instagram video not download

### ISSUE THREAD

**Issue by khizar1556** [iphoting/youtube-dl-api-server-heroku#30]
when i am trying to download video from instagram it gives error please check and update 

url : https://hamaraaweb.herokuapp.com/api/info?url=https://www.instagram.com/p/B5XVzdfnz9NR-yIj3rXvO1ZdyZXapVuzlL2idk0/

response: 
{"error":"ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."}

**Comment by iphoting** [comment]
It’s a private profile, nothing can be done.
