### ISSUE TITLE
how to download facebook/Instagram video that require user's auth 

### ISSUE THREAD

**Issue by darpanrajput** [iphoting/youtube-dl-api-server-heroku#42]
i am stuck at using the api where and how to provide the user name and password
for example i got this error
{
"error": "ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials."
}
but how to pass the username and password at this api format
i have established my heroku server
demo link :https://appname.herokuapp.com/api/info?url=https://www.facebook.com/zeemusiccompany/videos/785232881992360&flatten=True
The main url is:https://www.facebook.com/zeemusiccompany/videos/785232881992360
I have already logged in to Facebook but it still shows the same

**Comment by iphoting** [comment]
This usage is not supported by the upstream API: <https://youtube-dl-api-server.readthedocs.io/en/latest/api.html>.

**Comment by darpanrajput** [comment]
> This usage is not supported by the upstream API: https://youtube-dl-api-server.readthedocs.io/en/latest/api.html.
> 
> > **[API — youtube-dl-api-server 0.3 documentation](https://youtube-dl-api-server.readthedocs.io/en/latest/api.html)**
> 
> Workaround would be to install and run YouTube-DL locally.

But how all the android  app are getting video content using the same library..
There has to be way to implement this in android app..
Please help..
