### ISSUE TITLE
I got this error when i use the YouTube url

### ISSUE THREAD

**Issue by darpanrajput** [iphoting/youtube-dl-api-server-heroku#43]
"error":"ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."}

Though it is working fine for other social platforms but for every url of YouTube it shows this 
The url that i use https://appname.herokuapp.com/api/info?url=https://www.youtube.com/watch?v=zFbeyeQ2cCs&flatten=true

**Comment by iphoting** [comment]
As far as I recall, downloading from YouTube typically does not work with Heroku or AWS IP ranges. 

Workaround would be to install YouTube-DL and run it locally.

**Comment by darpanrajput** [comment]
> As far as I recall, downloading from YouTube typically does not work with Heroku or AWS IP ranges.
> 
> Workaround would be to install YouTube-DL and run it locally.

But i am developing an Android app ...
And before it was working very fine ..i tried lots of url end point but after some time it is getting this error
