### ISSUE TITLE
How to get updated youtube-dl packages?

### ISSUE THREAD

**Issue by abmspirit** [iphoting/youtube-dl-api-server-heroku#5]
I am very new to python.I have configured **youtube-dl-api-server-heroku**  on heroku using heroku ui.
Its working fine.Please tell me when youtube-dl will update its packages in future for more websites or for any bug issue. How will  i get these updates this on my heroku?

**Comment by iphoting** [comment]
On a periodic basis, I will overwrite the heroku branch with updated `requirements.txt`/`Pipefile.lock` files. 

There are 2 approaches that you can consider when that happens:
1. Redeploy your app using this repo's updated heroku branch; or
2. Merge this repo's updated heroku branch into your local working branch/copy and push to heroku for redeployment.
