### ISSUE TITLE
Deploy to Digital Ocean

### ISSUE THREAD

**Issue by toyinstark** [iphoting/youtube-dl-api-server-heroku#6]
Please can you make it easy to deploy this app to digital ocean. Heroku can be very expensive

**Comment by iphoting** [comment]
Are you referring to DigitalOcean Droplets? Those are bare-metal servers, please follow: 
- Installation: <https://youtube-dl-api-server.readthedocs.io/en/latest/install.html#using-pip>.
- Running the app via the included Procfile: <https://ddollar.github.io/foreman/>.
