### ISSUE TITLE
Outdated youtube-dl package

### ISSUE THREAD

**Issue by omarsinan** [iphoting/youtube-dl-api-server-heroku#7]
Currently, youtube-dl-api-server-heroku is not working for any YouTube video. If you try:

> https://<YOUR_APP_NAME>.herokuapp.com/api/info?url=https://www.youtube.com/watch?v=zBkVCpbNnkU

You will get the following error:
`error: "ERROR: zBkVCpbNnkU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."`

This issue has been closed here 

> https://github.com/ytdl-org/youtube-dl/issues/20769

 
in this commit: 

> https://github.com/ytdl-org/youtube-dl/commit/56667d622c3f6e7594a04f8cd5f4371875940725

Could you please update the youtube-dl package to the latest version? Or provide instructions on how to do so?

Thank you.

**Comment by iphoting** [comment]
> Could you please update the youtube-dl package to the latest version? 

Updated in 5af70f7f83770014b59795d354f97c7dc20ba8e4.

> Or provide instructions on how to do so?

Refer to: <https://github.com/iphoting/youtube-dl-api-server-heroku#updating-python-packages>.
